### PR TITLE
There's currently no advantage to using dual slow interleaved mode for a...

### PR DESCRIPTION
**Pull request by jablko**
...nalogRead()

See http://community.spark.io/t/why-dual-slow-interleaved/5550

### CODE REVIEW

**Comment by m-mcgowan** [comment]
ping @technobly

**Comment by m-mcgowan** [comment]
@technobly  is this still relevant for the core?

**Comment by technobly** [comment]
Absolutely swamped at the moment... but this is in our internal project tracking system currently, search ADC.  I'd suggest we add this to next Sprint.

This comment in the code that was deleted is particularly interesting: 
`#define ADC_SAMPLING_TIME ADC_SampleTime_7Cycles5 //Allowed values: 1.5, 7.5 and 13.5 for "Dual slow interleaved mode"`

**Comment by technobly** [comment]
Added to Clubhouse 1664.  Let's work on this one soon!

**Comment by jablko** [comment]
I think this issue is still relevant. Would you like me to rebase the PR on the latest firmware code?

**Comment by technobly** [comment]
Agreed, it's definitely relevant :)  I've added it to Clubhouse which is our internal issue tracker.  This PR may be reopened and used as-is, with rebase, or we may take it in a different direction.  The goal will be to give the ADC attention and make sure it is performing in the best way (full resolution sampling, high impedance requirements, while still allowing the users to reconfigure it for faster sample rates with the trade off of lower impedance requirements).  Nothing to do now, but if you'd like to rebase the PR, that would be welcome.  Thanks @jablko !

**Comment by technobly** [comment]
It should also be rebased against `develop`.

**Pull request closed without merging**
