### PR TITLE
tweaks for CI build

### PR DESCRIPTION
**Pull request by joegoggins**
Hey @m-mcgowan , let's use this branch + PR to make tweaks to firmware as needed as we iterate on our new CI tooling. We can also keep most of the discussion about the changes in one place (on the PR).  

- 04e8ed9 was done because CentOS does not have a `shasum` command, instead it has `sha256sum`. Though this change works for me--it will break builds for OS X, since it doesn't have `sha256sum`, would you be able to add a conditional to the make file. For a great example of how this logic looks in bash, check this out https://github.com/Leonidas-from-XIV/leiningen/commit/dfc57b8d357a40095811975360b2ac7706d8d15c

No need to merge this PR now, we'll do that at the end of the sprint after we vet and clean things up more.

### CODE REVIEW

**Comment by andyw-lala** [comment]
I think I opted for the "shasum -a 256" option in order to support macs
with the same fix back in the original PR (which I'll admit I never tested
on RHEL/CentOS) - at that time Mac & Windows were the active fw build
platforms. Knowingly breaking the build for macs is kind of bad form.

On Tue, Jul 14, 2015 at 4:56 PM, Joe Goggins <notifications@github.com>
wrote:

> Hey @m-mcgowan <https://github.com/m-mcgowan> , let's use this branch +
> PR to make tweaks to firmware as needed as we iterate on our new CI
> tooling. We can also keep most of the discussion about the changes in one
> place (on the PR).
>
>    - 04e8ed9
>    <https://github.com/spark/firmware/commit/04e8ed9d038563c12aaf66db5c22d6f79c671261>
>    was done because CentOS does not have a shasum command, instead it has
>    sha256sum. Though this change works for me--it will break builds for
>    OS X, since it doesn't have sha256sum, would you be able to add a
>    conditional to the make file. For a great example of how this logic looks
>    in bash, check this out Leonidas-from-XIV/leiningen@dfc57b8
>    <https://github.com/Leonidas-from-XIV/leiningen/commit/dfc57b8d357a40095811975360b2ac7706d8d15c>
>
> No need to merge this PR now, we'll do that at the end of the sprint.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/spark/firmware/pull/486
> Commit Summary
>
>    - tiny linux make tweak to work on CentOS: shasum -a 256 -> sha256sum
>
> File Changes
>
>    - *M* build/module.mk
>    <https://github.com/spark/firmware/pull/486/files#diff-0> (4)
>
> Patch Links:
>
>    - https://github.com/spark/firmware/pull/486.patch
>    - https://github.com/spark/firmware/pull/486.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark/firmware/pull/486>.
>



-- 
Andy

**Comment by joegoggins** [comment]
I 100% agree with you @andyw-lala , was just pushing some quick tweaks to get things working in CI environment we're building. We'll certainly circle back and fix this before merging back in. I expect other quick tweaks like this to pop up on this PR as we do this work, all of which we'll make sure to cleanup + ensure non-breaking changes before merging.

**Comment by joegoggins** [comment]
Thanks for the commits Mat. I've got the beginnings of build matrix enumeration happening in a CI context based on matrix.json.  I've got two issues I'll need your help resolving:

### 1 `PLATFORM=p1` fails in all cases

    ✓ make DEBUG_BUILD=n PLATFORM=core COMPILE_LTO=n SPARK_CLOUD=n
    ✓ make DEBUG_BUILD=n PLATFORM=core COMPILE_LTO=n SPARK_CLOUD=y
    ✓ make DEBUG_BUILD=n PLATFORM=core COMPILE_LTO=y SPARK_CLOUD=n
    ✓ make DEBUG_BUILD=n PLATFORM=core COMPILE_LTO=y SPARK_CLOUD=y
    ✗ make DEBUG_BUILD=n PLATFORM=p1 COMPILE_LTO=n SPARK_CLOUD=n
     (in test file DEBUG_BUILD-n__PLATFORM-p1__COMPILE_LTO-n__SPARK_CLOUD-n.bats, line 4)
       `make DEBUG_BUILD=n PLATFORM=p1 COMPILE_LTO=n SPARK_CLOUD=n' failed with status 2
     ../build/platform-id.mk:68: *** "Unknown platform: p1.  Stop.
    ✗ make DEBUG_BUILD=n PLATFORM=p1 COMPILE_LTO=n SPARK_CLOUD=y
     (in test file DEBUG_BUILD-n__PLATFORM-p1__COMPILE_LTO-n__SPARK_CLOUD-y.bats, line 4)
       `make DEBUG_BUILD=n PLATFORM=p1 COMPILE_LTO=n SPARK_CLOUD=y' failed with status 2
     ../build/platform-id.mk:68: *** "Unknown platform: p1.  Stop.
    ✗ make DEBUG_BUILD=n PLATFORM=p1 COMPILE_LTO=y SPARK_CLOUD=n
     (in test file DEBUG_BUILD-n__PLATFORM-p1__COMPILE_LTO-y__SPARK_CLOUD-n.bats, line 4)
       `make DEBUG_BUILD=n PLATFORM=p1 COMPILE_LTO=y SPARK_CLOUD=n' failed with status 2
     ../build/platform-id.mk:68: *** "Unknown platform: p1.  Stop.
    ✗ make DEBUG_BUILD=n PLATFORM=p1 COMPILE_LTO=y SPARK_CLOUD=y
     (in test file DEBUG_BUILD-n__PLATFORM-p1__COMPILE_LTO-y__SPARK_CLOUD-y.bats, line 4)
       `make DEBUG_BUILD=n PLATFORM=p1 COMPILE_LTO=y SPARK_CLOUD=y' failed with status 2
     ../build/platform-id.mk:68: *** "Unknown platform: p1.  Stop.
    ✓ make DEBUG_BUILD=n PLATFORM=photon COMPILE_LTO=n SPARK_CLOUD=n
    ✓ make DEBUG_BUILD=n PLATFORM=photon COMPILE_LTO=n SPARK_CLOUD=y
    ✓ make DEBUG_BUILD=n PLATFORM=photon COMPILE_LTO=y SPARK_CLOUD=n
    ✓ make DEBUG_BUILD=n PLATFORM=photon COMPILE_LTO=y SPARK_CLOUD=y
    ✓ make DEBUG_BUILD=y PLATFORM=core COMPILE_LTO=n SPARK_CLOUD=n
    ✓ make DEBUG_BUILD=y PLATFORM=core COMPILE_LTO=n SPARK_CLOUD=y
    ✓ make DEBUG_BUILD=y PLATFORM=core COMPILE_LTO=y SPARK_CLOUD=n
    ✓ make DEBUG_BUILD=y PLATFORM=core COMPILE_LTO=y SPARK_CLOUD=y
    ✗ make DEBUG_BUILD=y PLATFORM=p1 COMPILE_LTO=n SPARK_CLOUD=n
     (in test file DEBUG_BUILD-y__PLATFORM-p1__COMPILE_LTO-n__SPARK_CLOUD-n.bats, line 4)
       `make DEBUG_BUILD=y PLATFORM=p1 COMPILE_LTO=n SPARK_CLOUD=n' failed with status 2
     ../build/platform-id.mk:68: *** "Unknown platform: p1.  Stop.
    ✗ make DEBUG_BUILD=y PLATFORM=p1 COMPILE_LTO=n SPARK_CLOUD=y
     (in test file DEBUG_BUILD-y__PLATFORM-p1__COMPILE_LTO-n__SPARK_CLOUD-y.bats, line 4)
       `make DEBUG_BUILD=y PLATFORM=p1 COMPILE_LTO=n SPARK_CLOUD=y' failed with status 2
     ../build/platform-id.mk:68: *** "Unknown platform: p1.  Stop.
    ✗ make DEBUG_BUILD=y PLATFORM=p1 COMPILE_LTO=y SPARK_CLOUD=n
     (in test file DEBUG_BUILD-y__PLATFORM-p1__COMPILE_LTO-y__SPARK_CLOUD-n.bats, line 4)
       `make DEBUG_BUILD=y PLATFORM=p1 COMPILE_LTO=y SPARK_CLOUD=n' failed with status 2
     ../build/platform-id.mk:68: *** "Unknown platform: p1.  Stop.
    ✗ make DEBUG_BUILD=y PLATFORM=p1 COMPILE_LTO=y SPARK_CLOUD=y
     (in test file DEBUG_BUILD-y__PLATFORM-p1__COMPILE_LTO-y__SPARK_CLOUD-y.bats, line 4)
       `make DEBUG_BUILD=y PLATFORM=p1 COMPILE_LTO=y SPARK_CLOUD=y' failed with status 2
     ../build/platform-id.mk:68: *** "Unknown platform: p1.  Stop.
    ✓ make DEBUG_BUILD=y PLATFORM=photon COMPILE_LTO=n SPARK_CLOUD=n
    ✓ make DEBUG_BUILD=y PLATFORM=photon COMPILE_LTO=n SPARK_CLOUD=y
    ✓ make DEBUG_BUILD=y PLATFORM=photon COMPILE_LTO=y SPARK_CLOUD=n
    ✓ make DEBUG_BUILD=y PLATFORM=photon COMPILE_LTO=y SPARK_CLOUD=y

    24 tests, 8 failures

### 2 ci/unit_tests.sh doesn't work

    $ ./ci/unit_tests.sh
    cc1plus: error: unrecognized command line option "-std=gnu++11"
    make: *** [obj/core-firmware/user/tests/unit/catch.o] Error 1
    Error: Problem building unit tests

The first issue is almost definitely something you can fix in firmware-land.
The second issue seems like it could have to do with my version of gcc perhaps, `gcc --version` says `gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-11)`

Any ideas?

**Comment by m-mcgowan** [comment]
Howdy Joe! 

The first one is easy - it should be P1 (capital P) sorry! 

The second problem is definitely a compiler issue. C++11 wasn't introduced until gcc 4.7. I'm using version `gcc (Homebrew gcc49 4.9.2_1) 4.9.2`

**Comment by joegoggins** [comment]
Ha! Sweet, thanks. I now have both of these things fixed + working in CI-land. A couple of followup/refinement questions for ya:

Each execution of a permutation in the build matrix is just a bats script like this:

    @test "make DEBUG_BUILD=n PLATFORM=core COMPILE_LTO=n SPARK_CLOUD=n" {
      cd /spark/firmware_tests/main
      make DEBUG_BUILD=n PLATFORM=core COMPILE_LTO=n SPARK_CLOUD=n
      [ "$?" -eq 0 ]
    }

With the current matrix there are 24 permutations with no cleanup in between executing each one. Should there be a cleanup step or is this okay? Are there any other assertions you'd want to make on the output or build artifacts from make other than the exit code (like shown above) right now?

Cheers,

-j

**Comment by andyw-lala** [comment]
recommend you at least add the targets "clean all" to the make command
lines. That should build each from scratch.

With complex trees like this building multiple products, in the past I've
resorted to rm -rf  and a clean checkout before each test, just to make
sure there are no artifacts left over that get used because of loopholes in
the makefile rules. I regard disk and CPU as effectively infinite and free
for the purposes of CI.

You can speed things up by trying "make -j <n>" on multicore platforms, but
this didn't work well for me last time I tried it, so there must be some
implicit assumptions that the makefile was making, it would be worth
rechecking and fixing. I didn't track it down at the time, because I
figured I was probably the only person trying -j and didn't have time to
spend on it.

On Thu, Jul 16, 2015 at 12:31 AM, Joe Goggins <notifications@github.com>
wrote:

> Ha! Sweet, thanks. I now have both of these things fixed + working in
> CI-land. A couple of followup/refinement questions for ya:
>
> Each execution of a permutation in the build matrix is just a bats script
> like this:
>
> @test "make DEBUG_BUILD=n PLATFORM=core COMPILE_LTO=n SPARK_CLOUD=n" {
>   cd /spark/firmware_tests/main
>   make DEBUG_BUILD=n PLATFORM=core COMPILE_LTO=n SPARK_CLOUD=n
>   [ "$?" -eq 0 ]
> }
>
> With the current matrix there are 24 permutations with no cleanup in
> between executing each one. Should there be a cleanup step or is this okay?
> Are there any other assertions you'd want to make on the output or build
> artifacts from make other than the exit code (like shown above) right now?
>
> Cheers,
>
> -j
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark/firmware/pull/486#issuecomment-121836589>.
>



-- 
Andy

**Comment by joegoggins** [comment]
:+1: on `make clean all`, I did that, thanks. I'll get hefty with `rm -rf` if I see any troubles.

**Comment by m-mcgowan** [comment]
:+1: yep, a clean build is needed between each step since the make won't see that the targets are out of date. (I'd love to know how to factor the environment as a make dependency so when the environment changes the make is out of date.)

**Comment by joegoggins** [comment]
Alright folks, this PR is ready for merging into develop, I see the changes as low risk. 
This PR does 2 things:
- enumerates a 5 dimensional build matrix, that captures 72 different `make clean all` permutations (me)
- runs the unit tests (Mat)

@towynlin , how would you feel about merging this?

@andyw-lala , I believe I resolved the issues you raised with OS specific versions of `shasum` vs `sha256sum` via makefile tweak in 766a42a. Let me know if not.

@kennethlimcp , yes, parallel builds would speed this up a lot and is definitely something we should do in the future at some point.  I'd like to hold off for now though because it complicates the matrix enumeration logic. Once we're comfortable with this, have made a few refinements, and the logic is stable, we should revisit this and seek to parallelize.

**Pull request merged**
