### PR TITLE
cloud sleep - waits for all outgoing confirmable UDP messages to be sent (rebased)

### PR DESCRIPTION
**Pull request by technobly**
This PR is a rebase against develop of PR #909
* It fixes a lockup issue observed on the Photon and Electron
* If resolves merge conflicts with PR #909 and develop
* It changes the behavior a bit for the new NETWORK_STANDBY flag so that messages are still confirmed before going to sleep while the nework remains on.

Original PR #909 descriptions:
>protocol sleep/wake commands which allow the caller to wait for all coap confirmable requests to be acknowledged, and allows the comms layer to take action when waking up after sleep.

>This is used as part of system sleep to ensure confirmable messages are confirmed before entering sleep.

>https://github.com/spark/firmware/commit/3014dd53bee31f89222d25276504657e608b575d addresses issue #894 - the system will reconnect to the cloud before returning control back to the application loop after waking up. 

* To note, this only affects the Electron currently but could be adapted for Photon at a later time.
* Also only effective for Stop mode Sleep currently.
* Should this be implemented for Deep Sleep as well :question: See notes here: https://github.com/spark/firmware/pull/918/commits/fe44f22abe313a392a26775cbc1d188e88dc5fed
* Tested on the Electron with Sleep modes seen below.
* Tested with multi-threading enabled, however multi-threading is still in beta on Electron.

- [ ] Review code
- [x] Test on device
- [ ] Add documentation
- [ ] Add to changelog

## Test app
```c++
#include "application.h"

SYSTEM_MODE(SEMI_AUTOMATIC);

// ALL_LEVEL, TRACE_LEVEL, DEBUG_LEVEL, INFO_LEVEL, WARN_LEVEL, ERROR_LEVEL, PANIC_LEVEL, NO_LOG_LEVEL
Serial1DebugOutput debugOutput(9600, ALL_LEVEL);

retained int count = 0;

STARTUP(System.enableFeature(FEATURE_RETAINED_MEMORY));

void spinWait(uint32_t timeout) {
	uint32_t start = millis();
	while (millis() - start < timeout) Particle.process();
}

void setup() {
	pinMode(D1, INPUT_PULLDOWN);
	pinMode(D7, OUTPUT);
	Particle.connect();
	DEBUG_D("\r\n[ Particle.connect ]\r\n\r\n");
	waitUntil(Particle.connected);
	DEBUG_D("\r\n[ Particle.connected ]\r\n\r\n");
}

void loop() {

	digitalWrite(D7, LOW);
	DEBUG_D("\r\n[ Waking up and publishing once! ]\r\n\r\n");
    waitUntil(Particle.connected);
	Particle.publish("b", String(++count));

	// Does not require a delay between Publish and Sleep Stop mode anymore
	//spinWait(6000);

	DEBUG_D("\r\n[ Going to sleep ]\r\n\r\n");
	digitalWrite(D7, HIGH);

	// These all will restore and resume sessions after the first full handshake (fairly low data usage)
	//
	// System.sleep(D1, RISING, 30); // SLEEP_NETWORK_OFF is default
	// System.sleep(D1, RISING, 30, SLEEP_NETWORK_OFF); // Turns off network

	// These all require full handshakes (higher data usage)
	//
	// System.sleep(SLEEP_MODE_DEEP, 30); // SLEEP_NETWORK_OFF is default
	// System.sleep(SLEEP_MODE_DEEP, 30, SLEEP_NETWORK_STANDBY); // Does not turn off network
	// System.sleep(SLEEP_MODE_DEEP, 30, SLEEP_NETWORK_OFF); // Turns off network

	// This is the only one that doesn't require another
	// session resume or handshake upon waking (lowest data usage)
	//
	System.sleep(D1, RISING, 30, SLEEP_NETWORK_STANDBY); // Does not turn off network
}
```

### CODE REVIEW

**Comment by technobly** [comment]
@monkbroc please review when you have time, thanks!

@sergeuz @monkbroc please note the change to how SYSTEM_THREAD_CONTEXT_SYNC_CALL() is used vs in PR #909 which was causing the lockup.  Any comments/suggestions on this would be welcome as I haven't dived into the multi-threading as deeply as Mat has.

**Comment by monkbroc** [comment]
We need to do this review together @technobly. I don't know many of the terms used in this PR (lightssl, coap, dtls protocol).

**Comment by technobly** [comment]
Tested with multi-threading enabled and the test app above is working as expected, however of all the things that might not work when multi-threading is enabled... two of the DEBUG_D messages appear garbled the first time the app is executed.

```
DEBUG_D("\r\n[ Waking up and publishing once! ]\r\n\r\n");
DEBUG_D("\r\n[ Going to sleep ]\r\n\r\n");
```

All of the other ones are fine.

These look like this when garbled:
```
64.756 AT send      33 "\x17\xfe\xfd\x00\x01\x00\x00\x00\x00\x00\x10\x00\x14\x00\x01\x00\x00\x00\x00\x00\x10\xa5\tY\x1d\xd3\x99\xac\xc44\xa4U\xcc"
    65.004 AT read  +   16 "\r\n+USOST: 0,33\r\n"
    65.014 AT read OK    6 "\r\nOK\r\n"

[ Wakin   p6a.d42uAl seidg o c !6]"
                                   T
                                    USORF=0,813\r\n"
    65.112 AT read  +   76 "\r\n+USORF: 0,\"52.23.166.71\",5684,39,\"\x17\xfe\xfd\x00\x01\x00\x00\x00\x00\x00\x0f\x00\x1a\x00\x01\x00\x00\x00\x00\x00\x0f\x06\x90\x0e\x06\xcc1\xe3\xee\xf9\xbb\xb1zK\xd0 \xd3I)\""
    65.323 AT read OK    6 "\r\nOK\r\n"
// some lines removed to make this shorter - - - - - - - - -
    66.431 AT read  +   16 "\r\n+USOST: 0,40\r\n"
    66.441 AT read OK    6 "\r\nOK\r\n"

[ Going t  6l.4p9]A
                    
                    end      16 "AT+USORF=0,813\r\n"
    66.539 AT read  +   75 "\r\n+USORF: 0,\"52.23.166.71\",5684,38,\"\x17\xfe\xfd\x00\x01\x00\x00\x00\x00\x00\x10\x00\x19\x00\x01\x00\x00\x00\x00\x00\x10M<C\xf0\xbcVO\xceP\xbf\xd9\xa7\xadA\xd7\xc6\xe8\""
    66.743 AT read OK    6 "\r\nOK\r\n"
```

---

Because the change to SYSTEM_THREAD_CONTEXT_SYNC_CALL() is working while SYSTEM_THREAD() is ENABLED, I want to check out the System.on() events which has a similar call that could be a problem.

**Comment by monkbroc** [comment]
I reviewed the latest changes. It looks ready for merging.

**Pull request merged**
