### PR TITLE
Speed up I2C 100ms timeout on Slave_Address NACK - fixes #675

### LINKED ISSUE #675: Speed up I2C 100ms timeout on Slave_Address NACK with a flag
See discussion and proposed solution here: https://community.particle.io/t/issue-with-i2c-on-photon/12161/45

### PR DESCRIPTION
**Pull request by technobly**
* 100ms timeout is now immediately aborted if ACK failure is detected, i.e., no response to Slave Address being sent.  Master sees NACK on 9th SCL clock.
* NOTE: If Slave is disconnected, Master must still have pull up resistors on SDA and SCL to properly detect an ACK failure.  Without these, the I2C interface will see many Bus Errors (BERR) and potentially ARLO failure.
* Improved comments for I2C Receive routine (HAL_I2C_Request_Data())
* Added missing re-enable commands for interrupts in SW RESET function
* mode and ackFailure elements added to end of STM32_I2C_Info structure to preserve organization in memory for DYNALIB, allows older I2C apps to work with new I2C library.

### CODE REVIEW

**Comment by technobly** [comment]
Fixes: https://github.com/spark/firmware/issues/675

**Comment by m-mcgowan** [comment]
Regarding dynalib and the STM32_I2C_Info struct - that struct isn't passed out to other modules (the definition is in a C file so no sharing of the struct event). Thus it's only used internally within the I2C HAL meaning versioning isn't a concern here - feel free to place the new values where they make sense.

**Comment by technobly** [comment]
Ah ok cool, probably a good habit to get into anyway as structs rarely need to be organized :)

**Comment by m-mcgowan** [comment]
:+1:

**Comment by technobly** [comment]
Once I know this is working well for everyone, I can make the same changes to the Core.

**Pull request merged**
