### PR TITLE
Feature/added spare pins for P1

### PR DESCRIPTION
**Pull request by wesner0019**
I followed how the extra pins on the Electron were added and add the spare pins for the P1

### CODE REVIEW

**Comment by technobly** [comment]
@wesner0019 Noice!!  Thanks for paying attention :) I was going to add this along with the rest of the Electron pins this morning so you saved me some work.  Also, I think I'm going to change the pin names for the spare P1 to P1S0-P1S5 so they don't overlap with the Electron names that are already B0-B5 and C0-C5.  If you want to make that change, please feel free to do so, just add to your PR.  Also would you please read and sign this CLA: https://docs.google.com/a/spark.io/forms/d/1_2P-vRKGUFg5bmpcKLHO_qNZWGi5HKYnfrrkd-sbZoA/viewform

**Comment by wesner0019** [comment]
@technobly, changes should be made

**Comment by kennethlimcp** [comment]
Might want to consider squashing 4 commits into 1 ;)

**Comment by wesner0019** [comment]
@kennethlimcp, not sure how to do that. Just learning pull requests in git.

**Comment by wesner0019** [comment]
@Tchnolbly also noticed this is in for the Photon and P1, I think that this is incorrect for ADC on RX and TX. 
//MAY BE INCORRECT FOR THE PHOTON AND P1
 #define A8 18
 #define A9 19

**Comment by technobly** [comment]
Yes thanks!  This needs to be removed... once you sign the CLA I'll merge this in and continue adding to it.  Don't worry about squashing, it can be pretty tricky and frustrating if you've never done it or use VIM style editors.  Here's a decent video on the subject though that you can watch and digest later: https://www.youtube.com/watch?v=dxrVJC3uZ9s

**Comment by technobly** [comment]
@wesner0019 would appreciate your help testing these new pins on the P1 :)
Commit here: https://github.com/spark/firmware/commit/ca119e29ae2dbdc1f827794e0005b420775a461b

You'll need to build system and application firmware from the `develop` branch as follows from the `modules` directory:
`make clean all PLATFORM_ID=8 COMPILE_LTO=n APP=myapp -s PARTICLE_DEVELOP=1 program-dfu`

Your firmware goes in an app.cpp file that resides in:
`firmware/user/applications/myapp/app.cpp`

All extra pins should work as GPIO (P1S0~P1S5) and ADC (except for P1S4).
e.g. `pinMode(P1S0, OUTPUT); digitalWrite(P1S0, HIGH);`
The 2 extra PWMs may work because they are using timers that are already used... not sure.
These definitely won't work as tone() and may work as attachInterrupt()/sleep()...

**Comment by wesner0019** [comment]
@technobly, I tried flashing locally with the below myapp/app.cpp
But I got tons of errors like: 'A6' was not declared in this scope, etc Any ideas?


```cpp

#define LidSensorPin A6 
#define Buzzer D3 //Buzzer for sound notification
#define centerPin D4 //Center switch for tray alignment
#define motorPin4 P1S0	// Orange - 28BYJ48 pin 4 Stepper motor control
#define motorPin3 P1S1	// Yellow - 28BYJ48 pin 3 Stepper motor control
#define motorPin2 P1S2	// Pink   - 28BYJ48 pin 2 Stepper motor control
#define motorPin1 P1S3	// Blue   - 28BYJ48 pin 1 Stepper motor control
#define powerGood P1S4 //Open drain on LiPo charger, High = No/Bad AC power, low = GOOD AC power
#define Charger P1S5 //Open drain on LiPo charger, High when complete or disabled, low charging, flashing timer fault
boolean centerStatus = FALSE;
int motorSpeed = 1700;
int currStep = 1;

//SYSTEM_MODE(SEMI_AUTOMATIC);

void setup() {
    
    Serial.begin(9600);
    
    pinMode(Charger, INPUT_PULLUP);    //LiPo charging status
    pinMode(Buzzer, OUTPUT);    //Tone generator
    
    pinMode(centerPin, INPUT_PULLUP); //Battery volage readings
    pinMode(LidSensorPin, INPUT_PULLUP);  //Button press reading
    pinMode(motorPin1, OUTPUT); //stepper mortor pin
    pinMode(motorPin2, OUTPUT); //stepper mortor pin
    pinMode(motorPin3, OUTPUT); //stepper mortor pin
    pinMode(motorPin4, OUTPUT); //stepper mortor pin
    pinMode(powerGood, INPUT_PULLUP); //used to determine if external power is pugged in

    setMotor(0,0,0,0,0);    //Turns stepper motor off
    attachInterrupt(centerPin, centerTriggered, FALLING);
    delay(10);

    //Find 1st tray
    while (centerStatus == false){
        nextStep();
    }
    detachInterrupt(centerPin);   
}

void loop(void) {
    lidState = digitalRead(LidSensorPin);
    if(lidState == 0 && toneFirstTime == TRUE){
        tone(Buzzer, 2150);
        toneFirstTime = FALSE;
    }
    if(lidState == 1){
        noTone(Buzzer);
        toneFirstTime = TRUE;
    }
        
Serial.println(digitalRead(powerGood));
Serial.println(digitalRead(Charger));
delay(300);
    
}//loop



void nextStep(){

     switch (currStep) {
        case 1:
            setMotor(1,0,0,0,motorSpeed);
          break;
        case 2:
          setMotor(1,1,0,0,motorSpeed);
          break;
        case 3:
          setMotor(0,1,0,0,motorSpeed);
          break;
        case 4:
          setMotor(0,1,1,0,motorSpeed);
          break;
        case 5:
          setMotor(0,0,1,0,motorSpeed);
          break;
        case 6:
          setMotor(0,0,1,1,motorSpeed);
          break;
        case 7:
          setMotor(0,0,0,1,motorSpeed);
          break;
        case 8:
          setMotor(1,0,0,1,motorSpeed);
          break;
      }

      setMotor(0,0,0,0,0);    //Turns stepper motor off


      currStep++;
      if(currStep > 8){
        currStep = 1;
      }
}

void setMotor(int8_t pin1, int8_t pin2, int8_t pin3, int8_t pin4, int theDelay){

    if(pin1 == 1){
        digitalWrite(motorPin1, HIGH);
    } else {
        digitalWrite(motorPin1, LOW);
    }
    if(pin2 == 1){
        digitalWrite(motorPin2, HIGH);
    } else {
        digitalWrite(motorPin2, LOW);
    }
    if(pin3 == 1){
        digitalWrite(motorPin3, HIGH);
    } else {
        digitalWrite(motorPin3, LOW);
    }
    if(pin4 == 1){
        digitalWrite(motorPin4, HIGH);
    } else {
        digitalWrite(motorPin4, LOW);
    }

    delayMicroseconds(theDelay);
}

void centerTriggered(){
	centerStatus = true;
}
```

**Comment by wesner0019** [comment]
@technobly, I'm trying to build locally but have not been able to flash my user code successfully yet.

**Comment by wesner0019** [comment]
@technobly,  i have tested what I can with my P1 which is on a custom PCB.
I verified the below work:
digitalWrite on P1S0, P1S1, P1S2, P1S3
digitalRead on P1S4
analogRead on P1S5

```cpp
#define motorPin4 P1S0  // Orange - 28BYJ48 pin 4 Stepper motor control
#define motorPin3 P1S1  // Yellow - 28BYJ48 pin 3 Stepper motor control
#define motorPin2 P1S2  // Pink   - 28BYJ48 pin 2 Stepper motor control
#define motorPin1 P1S3  // Blue   - 28BYJ48 pin 1 Stepper motor control
#define powerGood P1S4 //Open drain on LiPo charger, High = No/Bad AC power, low = GOOD AC power
#define StepperForcePin P1S5 //Open drain on LiPo charger, High when complete or disabled, low charging, flashing timer fault

    pinMode(motorPin1, OUTPUT); //stepper mortor pin
    pinMode(motorPin2, OUTPUT); //stepper mortor pin
    pinMode(motorPin3, OUTPUT); //stepper mortor pin
    pinMode(motorPin4, OUTPUT); //stepper mortor pin
    pinMode(powerGood, INPUT_PULLUP); //used to determine if external power is pugged in
    pinMode(StepperForcePin, INPUT); // used to determine if extra force in being applied on the stepper motor
```

**Comment by technobly** [comment]
@wesner0019 that's super great!  Glad to hear you are unblocked and whizzing away on coding ;-)  I'll keep this open until we have a chance to test all of the functions of the new pins.  Thanks again for your help!

**Pull request merged**
