### PR TITLE
Adding DAC and WKP pin constants for Photon

### PR DESCRIPTION
**Pull request by paulmand3l**

### CODE REVIEW

**Comment by m-mcgowan** [comment]
Hey there @paulmand3l! Thanks for having a go at this. The firmware for the photon is in the "latest" branch at present, where DAC1, DAC2 and WKP are already defined. Please see https://github.com/spark/firmware/blob/latest/hal/inc/pinmap_hal.h#L112 and a little further down in that file for the DAC1 and DAC2 constants.

**Comment by paulmand3l** [comment]
Got it. Thanks! I'll file any further PR's over there.

On Thursday, July 23, 2015, Matthew McGowan <notifications@github.com>
wrote:

> Hey there @paulmand3l <https://github.com/paulmand3l>! Thanks for having
> a go at this. The firmware for the photon is in the "latest" branch at
> present, where DAC1, DAC2 and WKP are already defined. Please see
> https://github.com/spark/firmware/blob/latest/hal/inc/pinmap_hal.h#L112
> and a little further down in that file for the DAC1 and DAC2 constants.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark/firmware/pull/504#issuecomment-124245798>.
>


-- 
Sent from my iPhone.

**Comment by m-mcgowan** [comment]
Great, I look forward to that!

**Comment by m-mcgowan** [comment]
Referenced the wrong issue - the two commits above should reference #531

**Pull request closed without merging**
