### PR TITLE
Work around a WICED bug crashing when socket connection fails

### LINKED ISSUE #516: Photon: PANIC when TCPClient fails to connect
When trying to connect to a closed port or just failing to connect, the Photon restarts with an SOS instead of simply returning false.

Update:
- crashes and restarts w a PANIC if you try to connect right after the unit has connected to the internet (if you wait 2 seconds it works, less and it fails)
- crashes and restart w a PANIC if: address doesn't exist, nobody is listening on the port or if the tcp connection fails after a successful connect

### PR DESCRIPTION
**Pull request by monkbroc**
The reason for the bug is WICED deallocating the connection handler twice.

It occurs because in `WICED/network/LwIP/WICED/tcpip.c:920` the `netconn_delete( socket->conn_handler );` is not followed by `socket->conn_handler = NULL;` as it is in other places in the code for example in `WICED/network/LwIP/WICED/tcpip.c:931`. This leads `wiced_tcp_delete_socket` to delete the connection handler again, leading to a crash.

This should fix #516 and #490. @andyw-lala can you run your tests against this branch please?

This should also be reported to Broadcom so they can fix this upstream.

### CODE REVIEW

**Comment by andyw-lala** [comment]
So this would allow us to continue calling the upper level shutdown/disconnect functions, which should take care of housekeeping better ?

**Comment by monkbroc** [comment]
> So this would allow us to continue calling the upper level shutdown/disconnect functions, which should take care of housekeeping better ?

Correct.

I reverted afd45d2e before implementing the fix.

**Comment by andyw-lala** [comment]
I can apply and test tonight (US time).

**Comment by andyw-lala** [comment]
Test started. Might not be able to check in on the results for a few hours (see also: life)

**Comment by monkbroc** [comment]
Life? Don't talk to me about life.
-- Marvin

**Comment by andyw-lala** [comment]
Still fails after the same number of passes (approx 350), with the same syndrome.

My guess is we're still running the wiced stack out of resources, or memory, or perhaps the whole photon out of memory - I lack the diagnostic to dump the current size of the memory pool, or we could see if there was a leak in effect.

**Comment by monkbroc** [comment]
That's a really disappointing lack of quality in WICED :-(

**Comment by stevie67** [comment]
I would like to debug this in a bit more depth. Which version of the WICED SDK is needed to debug this further and is there a guide how to install it?

**Comment by monkbroc** [comment]
@stevie67 @m-mcgowan commented in another issue that Particle is in discussion with Broadcom for a permissive license to WICED. Right now they use WICE 3.3.0 with some modifications that they are not allowed to share with the community.

However, if you agree to Broadcom's terms, you can join the [WICED community](http://community.broadcom.com/community/wiced-wifi), [download the SDK](http://community.broadcom.com/community/wiced-wifi/wiced-wifi-documentation) and [download the Photon platform files](http://community.broadcom.com/community/wiced-wifi/wiced-wifi-forums/blog/2014/11/04/bcm9wcdusi09-platform-files-for-sdk-3x).

You can compile WICED with `./make snip.scan-BCM9WCDUSI09-FreeRTOS-LwIP-SDIO`. Althrough that library won't be compatible with the Photon build right now, it's still good enough to follow along what's going on and debug. (I adapted the WICED compile command from `hal/src/photon/wiced.sh`)

**Comment by monkbroc** [comment]
What's your test case again @andyw-lala? I don't remember in which thread you posted it...

**Comment by stevie67** [comment]
Thanks @monkbroc, I had joined the WICED community, just needed to know, which one to download. I will try that.

**Comment by andyw-lala** [comment]
Here's the test I'm using:

```cpp
TCPClient client;

IPAddress server1(192,168,121,34); /* This server does not exist */
IPAddress server2(192,168,121,51); /* This server exists and has an open http port */
int port = 80;

unsigned loop_count = 0;

void handler(const char *topic, const char *data)
{
    Serial1.println("received " + String(topic) + ": " + String(data));
}

void setup() {
  Serial1.begin(115200);
  Serial1.println("********************** RESTART ***********************");
  
  Spark.subscribe("spark/", handler);
}

void loop() {
  int x;
  
  Serial1.println("connecting to server1 (loop: " + String(loop_count) + ")");
  x = client.connect(server1, port);
  Serial1.println("   connect returned: " + String(x));
  x = client.println("Hello World!");
  Serial1.println("   println returned: " + String(x));
  x = client.connected();
  Serial1.println("   connected returned: " + String(x));

  if (x) {
    client.stop();
  }

  delay(2000);
  
  Serial1.println("connecting to server2 (loop: " + String(loop_count) + ")");
  x = client.connect(server2, port);
  Serial1.println("   connect returned: " + String(x));
  x = client.println("Hello World!");
  Serial1.println("   println returned: " + String(x));
  x = client.connected();
  Serial1.println("   connected returned: " + String(x));

  if (x) {
    client.stop();
  }

  Spark.publish("spark/device/name");
  delay(2000);
  loop_count++;
}
```

See the commnents for server1 vs server2.

The output is as follows:

********************** RESTART ***********************
connecting to server1 (loop: 0)
   connect returned: 0
   println returned: -3
   connected returned: 0
connecting to server2 (loop: 0)
   connect returned: 1
   println returned: 14
   connected returned: 1
connecting to server1 (loop: 1)
   connect returned: 0
   println returned: -3
   connected returned: 0
connecting to server2 (loop: 1)
   connect returned: 1
   println returned: 14
   connected returned: 1
received spark/device/name: andyw-201
connecting to server1 (loop: 2)
   connect returned: 0
   println returned: -3
   connected returned: 0
received spark/device/name: andyw-201
connecting to server2 (loop: 2)
   connect returned: 1
   println returned: 14
   connected returned: 1
...
connecting to server1 (loop: 349)
   connect returned: 0
   println returned: -3
   connected returned: 0
connecting to server2 (loop: 349)
   connect returned: 1
   println returned: 14
   connected returned: 1
received spark/device/name: andyw-201
connecting to server1 (loop: 350)
   connect returned: 0
   println returned: -3
   connected returned: 0
connecting to server2 (loop: 350)
   connect returned: 1
   println returned: 14
   connected returned: 1
connecting to server1 (loop: 351)
   connect returned: 0
   println returned: -3
   connected returned: 0
connecting to server2 (loop: 351)
   connect returned: 1
   println returned: 14
   connected returned: 1
connecting to server1 (loop: 352)
   connect returned: 0
   println returned: -3
   connected returned: 0
connecting to server2 (loop: 352)
   connect returned: 1
   println returned: 14
   connected returned: 1
connecting to server1 (loop: 353)
   connect returned: 0
   println returned: -3
   connected returned: 0
connecting to server2 (loop: 353)
   connect returned: 1
   println returned: -20
   connected returned: 1
connecting to server1 (loop: 354)
   connect returned: 0
   println returned: -3
   connected returned: 0
connecting to server2 (loop: 354)
   connect returned: 1
   println returned: -48
   connected returned: 1
connecting to server1 (loop: 355)
...
connecting to server2 (loop: 360)
   connect returned: 0
   println returned: -3
   connected returned: 0
connecting to server1 (loop: 361)
   connect returned: 0
   println returned: -3
   connected returned: 0
connecting to server2 (loop: 361)
   connect returned: 0
   println returned: -3
   connected returned: 0
connecting to server1 (loop: 362)
   connect returned: 0
   println returned: -3
   connected returned: 0
connecting to server2 (loop: 362)
...

You can see how it starts off working well, and staying in contact with the cloud (proven by the pub/sub resulting in printing of the photon's device name. That seems to be the first casualty (around  pass 350), then the connection to server2 (the one that exists) starts acting up, with return values of -20 and -48 from client.println(), finally it settles down to a steady-state failure mode around loop 360.

**Comment by andyw-lala** [comment]
Here's the pcap file that corresponds to the behaviour reported above. It might be missing some of the start of the test, but it certainly captures the end of the photon's connectivity.

https://www.dropbox.com/s/8y6kee36rrlkykv/516-soak-test-20150814-1.pcap?dl=0

**Comment by m-mcgowan** [comment]
Andy, just to be sure I'm undrstanding correctly - are you saying that there's still a resource leak even with this fix?  I'll add a memory available function to the HAL.

**Comment by andyw-lala** [comment]
Yes- with all the latest fixes, after 350 iterations of my test, the photon is dead to the network. At this point I do not know if it is a vanilla memory exhaustion problem, or if it is some other limitation buried in the wiced stack; but we're running out of *something*.

**Comment by m-mcgowan** [comment]
Thanks. So this fix neither helps nor hinders the firmware? I'm surprised since this is what I would have expected to fix things and avoid the double delete. I think I'll merge this fix all the same and make a rc.3 release, since we are already many steps ahead of where we were with the 0.4.4-rc.2 release.

**Comment by andyw-lala** [comment]
It's better, that's for sure.
Let me know when you've got a memfree call I can invoke every time around the loop of my testing.

**Comment by andyw-lala** [comment]
Confirmed with 2fa9708 the long term failure remains.

**Comment by monkbroc** [comment]
I think Particle needs to a serious memory management review of `hal/src/photon/socket_hal.cpp`.

There are several sketchy things going on in that file.

In `socket_create()`, memory is allocated for the Particle socket type `socket_t`: `socket_t* socket = new socket_t();`

`socket_create()` also contains `sock_handle_t result = SOCKET_INVALID;` (line 867) and the only other place it's used is in `socket_dispose(result);` (line 880). That's a relic from previous versions.

If the socket creation fails `wiced_result!=WICED_SUCCESS`, the `socket` memory allocated is not deallocated, or tracked anywhere.

If socket creation succeeds, the socket is added to a linked list (either `servers` or `clients`).

However, that linked list is never cleaned. The `clients` list had 775 Particle `socket_t` in it when @andyw-lala's test code stopped working. The only place where `socket_t` are deleted is in `remove_disposed_list` but that's never called in the current firmware.

So yeah, any code that uses sockets for a long time will eventually run out of RAM in the micro.

**Comment by m-mcgowan** [comment]
> If the socket creation fails wiced_result!=WICED_SUCCESS, the socket memory allocated is not deallocated, or tracked anywhere.

The code path in `socket_create()` either adds it to the list or the socket memory is reclaimed by a call to  `socket_dispose()`.  I'd removed the `delete` call in socket_dispose while we were investigating SOS's to eliminate memory bugs in our code. Now we have this fix, I can re-instatate that an also verify that the lists are cleaned up appropriately.

**Comment by m-mcgowan** [comment]
In the develop branch I've added resource cleanup, but there's definitely still a leak coming from WICED. 

Test case is to just connect to a non-existent port. With the normal code, I see a memory leak. If I comment out wiced_tcp_connect() in socket_hal and hard-wire to failure result, the lead disappears. 

So there's definitely a leak in WICED code. Once memory is exhausted, the cloud connection cannot be re-established. 

Unlike the Core, exhausted memory doesn't presently cause a PANIC, the intent being that we will later be adding better memory management with soft caches and the like. For now, I will introduce a panic on exhausted heap so we can see when the system has exhausted resources.

**Comment by m-mcgowan** [comment]
After re-instating the delete and list management, my test case is showing no leaks at all after thousands of both successful and failed socket connection attempts.

**Comment by andyw-lala** [comment]
Sorry, I forgot to post the commit I tested against, and now I'm out for
dinner. I'll post the commit as soon as we get home, but I did a git pull
about 20 mins before I sent my last update.

**Comment by monkbroc** [comment]
That's good news Matt! No crashes and no leaks. That's a huge improvement from last week :rocket:

**Comment by andyw-lala** [comment]
Using the new System.freeMemory() call, as of 3ab6ef7:

********************** RESTART ***********************
connecting to server1 (loop: 0)
   connect returned: 0
   println returned: -3
   connected returned: 0
connecting to server2 (loop: 0)
   connect returned: 1
   println returned: 14
   connected returned: 1
Heap: 60984
...
received spark/device/name: andyw-201
connecting to server1 (loop: 25)
   connect returned: 0
   println returned: -3
   connected returned: 0
connecting to server2 (loop: 25)
   connect returned: 1
   println returned: 14
   connected returned: 1
Heap: 60984


Nice work everyone. Early indications are that it's fixed - I'll leave the test running overnight & report back.

Now onto: #538, #536 & TCPClient::connected() [I don't think there's an issue opened for the connected(0 problem, or is it already fixed ?

**Comment by m-mcgowan** [comment]
Great, thanks for confirming. I'm not sure exactly what the TCPClient::connected() issue is - if there isn't already an issue for that, I'd be grateful if someone could write it up.

**Comment by monkbroc** [comment]
> TCPClient::connected() 

That's still an issue. Can `wiced_tcp_register_callbacks` come back to fix this?

**Comment by stevie67** [comment]
Same for me. I am using the System.freeMemory() call (many thanks for that @m-mcgowan). With the newest version it does not leak memory anymore, did for the earlier version - which I did not realize because in my test case the memory leak was so small and it occurred so infrequently. And it still handles the failing connection gracefully. Thanks to @monkbroc and @m-mcgowan and all others involved! This makes the Photon usable in real projects...

**Comment by andyw-lala** [comment]
So, 12 hours later - the free memory has changed, but there appears to be no persistent leak:

...
received spark/device/name: andyw-201
connecting to server1 (loop: 4142)
   connect returned: 0
   println returned: -3
   connected returned: 0
connecting to server2 (loop: 4142)
   connect returned: 1
   println returned: 14
   connected returned: 1
Heap: 57192
...

**Comment by nlambuca** [comment]
I am facing the same here...
If you do 500mS loops gets even worst.
I am using a local webserver, but it is possible that a connection request not always returns OK.

The smaller the loop time, the easier to make it fail.

This is still open with 0.4.6 photon fw, right?

**Pull request merged**
