### PR TITLE
private mbedtls in communications library

### PR DESCRIPTION
**Pull request by m-mcgowan**
the mbedtls headers are private to the communications module so applications can include their own version of mbedtls

---

Doneness:

- [x] Contributor has signed CLA
- [x] Problem and Solution clearly stated
- [x] Code peer reviewed
- [x] API tests compiled
- [x] Run unit/integration/application tests on device
- [ ] Add documentation
- [ ] Add to CHANGELOG.md after merging (add links to docs and issues)

### CODE REVIEW

**Comment by m-mcgowan** [comment]
Testing (mdma):
- [ ] compile system firmware and verify Electron can connect to the cloud.

**Comment by technobly** [comment]
@m-mcgowan wiring/no_fixture tests pass on Electron U260 as well as connecting and restoring sessions with the tinker usb debugging v0.4.8-rc.6 app.

**Comment by technobly** [comment]
It might be nice to add some kind of bare minimum example to the Docs of what someone can do with this now in User firmware.

**Comment by m-mcgowan** [comment]
That's not quite how it is - it's not in user firmware, it's still private - the changet allows developers to include their own copy of mbedtls in user firmware without conflicts from the system copy.

**Comment by technobly** [comment]
Oh is that kind of beyond the scope of our Docs?  They would have to acquire a copy of mbedtls, and can't duplicate anything used in our stack?

**Comment by rayjanwilson** [comment]
When we include our own, this allows us to push data to services like AWS that require an SSL/TLS connection? Essentially bypassing webhooks?

**Comment by m-mcgowan** [comment]
@rayjanwilson, yes potentially.

**Pull request merged**
