### PR TITLE
Improve EEPROM stability and persistence

### PR DESCRIPTION
**Pull request by monkbroc**
### Changes
* [Don't erase a page of flash ON EVERY BOOT](https://github.com/monkbroc/firmware/blob/18eda04106ea7f54d1a4a794840aa2403dad28bd/hal/src/stm32f2xx/eeprom_hal.c#L539) to increase Flash life and avoid erasing Flash in every low power situations
* Don't format the EEPROM in case both pages are valid, just erase one
* Lock the Flash after initialization or variable write

### Background

Bad chargers and depleted batteries cause the EEPROM contents to be lost on the Photon and Electron.
http://community.particle.io/t/eeprom-persistence-issue/16514
https://community.particle.io/t/photon-ran-low-on-battery-now-stuck-in-sos/16710
#704

The root cause is still not clear but one factor making it worse is the fact that the STM EEPROM emulation code (AN3390) erases one page of Flash on every boot. This is unnecessary and aweful for Flash life. Also what happens exactly if the microcontroller looses power during this erase operation? Experience shows that the EEPROM contents will be lost.

This is not a complete fix since an EEPROM erase could still happen during a low battery situation, but it will decrease the occurence of these issues.

### Steps to reproduce EEPROM persistence issue

1. Flash this application code

```
#include "application.h"

// Write something to the EEPROM on demand
int eepromWrite(String value) {
  EEPROM.write(0, 0xA5);
  return 0;
}

void setup()
{
  RGB.control(true);
  if(EEPROM.read(0) == 0xFF) {
    // Red means the EEPROM was wiped
    RGB.color(255, 0, 0);
  } else {
    // Yellow means the EEPROM was preserved
    RGB.color(255, 255, 0);
  }
  Particle.function("eepromWrite", eepromWrite);
}
```

2. Call `particle call device eepromWrite`
3. Reboot the Photon and notice the yellow LED meaning EEPROM contents are saved
4. Unplug the USB
5. Replug it partially, fiddle with it, making sure the white LED turn on and off multiple times and even turns partially on
6. Plug USB firmly
7. Notice the red LED meaning the EEPROM contents were lost. Try again if it doesn't fail on the first try

[Video of failure before the fix](https://youtu.be/YSzFfkvTlE8)
[Video of correct behavior after the fix](https://youtu.be/iKj_9vaid5A)

### CODE REVIEW

**Comment by nicodegunst** [comment]
Just tested this pull request, it absolutely works! Without it, I can very easily erase/corrupt the flash memory by simply switching usb on and off quickly (once or twice is enough). With this fix in place, I was unable to erase or corrupt the flash memory!

**Comment by m-mcgowan** [comment]
Perfect! Thank you @nicodegunst  for testing and verifying the fix. I'll review the code and apply this or something similar to the system firmware for the 0.4.8 release.

**Comment by towynlin** [comment]
:+1: Outstanding! Thanks so much Julien!

**Comment by monkbroc** [comment]
@m-mcgowan @towynlin You're welcome!

STM's EEPROM emulation code is pretty rancid. This PR is a quick fix for the worst issues, but I wouldn't be surprised if there are other failure modes in there like @andyw-lala believes.

**Comment by m-mcgowan** [comment]
Just to echo Zac's comment above, a big thanks for this! Catching the unnecessary erase on each boot is a big win.  It's been on my mind for a long time to refactor this code to be testable and verify with tests that erases don't happen more often than required, but it's continually been pushed down the list by other priorities.  Great to have an expert pair of eyes review the code. :+1:

**Comment by andyw-lala** [comment]
And it's official - no one is happier than me to see this step taken.

As Julien says, I believe there are likely to be other issues (rancid is an
understatement wrt AN3390), but never let perfection get in the way of
progress.

On Mon, Dec 14, 2015 at 12:05 PM, Matthew McGowan <notifications@github.com>
wrote:

> Just to echo Zac's comment above, a big thanks for this! Catching the
> unnecessary erase on each boot is a big win. It's been on my mind for a
> long time to refactor this code to be testable and verify with tests that
> erases don't happen more often than required, but it's continually been
> pushed down the list by other priorities. Great to have an expert pair of
> eyes review the code. [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark/firmware/pull/762#issuecomment-164512511>.
>



-- 
Andy

**Comment by m-mcgowan** [comment]
"but never let perfection get in the way of progress." What do you mean there @andyw-lala?

**Comment by andyw-lala** [comment]
Meaning that a fix that fixes the biggest problems but may not address
every single less common failure case, is to be preferred vastly over
holding out for the perfect fix to all problems (not that I believe anyone
was pushing for that in this case.)

It wasn't a loaded or sarcastic remark, if that's the way it came across.


On Mon, Dec 14, 2015 at 12:43 PM, Matthew McGowan <notifications@github.com>
wrote:

> "but never let perfection get in the way of progress." What do you mean
> there @andyw-lala <https://github.com/andyw-lala>?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark/firmware/pull/762#issuecomment-164522055>.
>



-- 
Andy

**Comment by monkbroc** [comment]
👍

Enjoy your holidays Mat.

**Comment by m-mcgowan** [comment]
Thanks very much for the good wishes and this PR. I'd like to get the brownout reset logic in place, so I might pick your brains about that in the new year! 

I hope you find time to relax over the holidays.  Festive greetings! :-)

**Comment by peterqu** [comment]
Hi @monkbroc 

Thank you for this great fix.  There is one minor thing I want to check with you.

For the case where page0=valid, page1=valid, the new change is to only erase page 0.  I think you have forgot to set page0 status to ERASED.  I think the current code will result in both page0 and page1 have the VALID_PAGE status, but page0 will contains all FF data (erased).

What do you think?

~~~c
// Line 522, page0=VALID, page1=VALID
 if (PageStatus1 == VALID_PAGE) /* Harmless invalid state -> pick one page and format the other */
 {
        /* Erase Page0 */
        FlashStatus = FLASH_EraseSector(PAGE0_ID, VOLTAGE_RANGE);
        /* If erase/program operation was failed, a Flash error code is returned */
        if (FlashStatus != FLASH_COMPLETE)
         {
                    return FlashStatus;
         }
        // I think you need to add this line 
        FlashStatus = FLASH_ProgramHalfWord(PAGE0_BASE_ADDRESS, ERASED);
}
~~~

**Comment by m-mcgowan** [comment]
ERASED is 0xFFFF so writing this has no affect when written to a freshly erased page.

**Comment by peterqu** [comment]
Great, then it's all good.

**Comment by andyw-lala** [comment]
In addition to avoiding gratuitous sector erase operations, Julien's fix
also only unlocks the flash controller during the required operations, and
locks the controller again afterwards. The original code appears to have
unlocked the controller regardless and left it unlocked, which is an
accident waiting to happen.

Since there is discussion about brownout protection, we should also take
steps to ensure the the flash configuration (see section 2.4 and 2.5 of
PM0059 (
http://www.st.com/web/en/resource/technical/document/programming_manual/CD00233952.pdf)
is supported by the voltage settings of the brownout controller.

It certainly looks like bad things can happen just reading flash at low
voltages, and it would be far better to just hold the part in reset rather
than execute unreliably. With Julien's fixes in place, I think the
opportunity for flaky operation due to low voltage will no longer corrupt
data required for reliable operation, but we should at least audit the
settings to ensure devices either operate reliably or not at all.

On Wed, Dec 23, 2015 at 2:35 AM, Peter Qu <notifications@github.com> wrote:

> Great, then it's all good.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark/firmware/pull/762#issuecomment-166833649>.
>



-- 
Andy

**Pull request merged**
