### PR TITLE
Low latency (direct) interrupt handlers

### LINKED ISSUE #1168: As a user, I'd like a way to create low latency interrupts, even if this is just a documented method and not necessarily wrapped up in a Wiring API
There are occasions where people would be willing to trade HW independence (HAL) for speed.
One of the occasions are interrupts.
The HAL seems to introduce a 5µs latency of EXTI and HW timer interrupts, which limits the usefulness for some projects considerably.
@pkourany and I had brought this forward before (several times), so I wanted to have this listed here to keep it on the radar.
I tried this, but the bare metal approach didn't work at all and the `attachInterrupt()` exhibited a minimum latency of 3µs where some 100ns should be possible.
```cpp
/**
 *	based on external interrupts example
 *
 *	@author 	Tilen Majerle
 *	@email		tilen@majerle.eu
 *	@website	http://stm32f4-discovery.com
 *	@ide		Keil uVision 5
 *  https://stm32f4-discovery.net/2014/08/stm32f4-external-interrupts-tutorial/
 */
//#include "stm32f2xx.h"
//#include "stm32f2xx_exti.h"
//#include "stm32f2xx_syscfg.h"
//#include "misc.h"

volatile uint32_t d2;
volatile uint32_t d3;
volatile uint32_t d4;

volatile uint32_t us;
volatile uint32_t us2;
volatile uint32_t us3;
volatile uint32_t us4;

uint32_t offset;

#undef EXTI4_IRQHandler
#undef EXTI9_5_IRQHandler

/* Set interrupt handlers */
/* Handle PB4 interrupt */
void EXTI4_IRQHandler(void) {
	/* Make sure that interrupt flag is set */
	if (EXTI_GetITStatus(EXTI_Line4) != RESET) {
		/* Do your stuff when PB4 is changed */
		
        us3 = SYSTEM_TICK_COUNTER;
        d3++;

		/* Clear interrupt flag */
		EXTI_ClearITPendingBit(EXTI_Line4);
	}
}

/* Handle PB5 interrupt */
void EXTI9_5_IRQHandler(void) {
	us2 = SYSTEM_TICK_COUNTER;
    d2++;

	/* Make sure that interrupt flag is set */
	if (EXTI_GetITStatus(EXTI_Line5) != RESET) {
		/* Do your stuff when PB5 is changed */
		

		/* Clear interrupt flag */
		EXTI_ClearITPendingBit(EXTI_Line5);
	}
}

/* Configure D3 for bare metal interrupt */
void Configure_PB4(void) {
	/* Set variables used */
	GPIO_InitTypeDef GPIO_InitStruct;
	EXTI_InitTypeDef EXTI_InitStruct;
	NVIC_InitTypeDef NVIC_InitStruct;
	
	/* Enable clock for GPIOD */
	RCC_AHB1PeriphClockCmd(RCC_AHB1Periph_GPIOB, ENABLE);
	/* Enable clock for SYSCFG */
	RCC_APB2PeriphClockCmd(RCC_APB2Periph_SYSCFG, ENABLE);
	
	/* Set pin as input */
	GPIO_InitStruct.GPIO_Mode = GPIO_Mode_IN;
	GPIO_InitStruct.GPIO_OType = GPIO_OType_PP;
	GPIO_InitStruct.GPIO_Pin = GPIO_Pin_4;
	//GPIO_InitStruct.GPIO_PuPd = GPIO_PuPd_UP;
	GPIO_InitStruct.GPIO_PuPd = GPIO_PuPd_DOWN;
	GPIO_InitStruct.GPIO_Speed = GPIO_Speed_100MHz;
	GPIO_Init(GPIOB, &GPIO_InitStruct);
	
	/* Tell system that you will use PB4 for EXTI_Line4 */
	SYSCFG_EXTILineConfig(EXTI_PortSourceGPIOB, EXTI_PinSource4);
	
	/* PB4 is connected to EXTI_Line4 */
	EXTI_InitStruct.EXTI_Line = EXTI_Line4;
	/* Enable interrupt */
	EXTI_InitStruct.EXTI_LineCmd = ENABLE;
	/* Interrupt mode */
	EXTI_InitStruct.EXTI_Mode = EXTI_Mode_Interrupt;
	/* Triggers on rising and falling edge */
	EXTI_InitStruct.EXTI_Trigger = EXTI_Trigger_Rising;
	//EXTI_InitStruct.EXTI_Trigger = EXTI_Trigger_Falling;
	//EXTI_InitStruct.EXTI_Trigger = EXTI_Trigger_Rising_Falling;
	/* Add to EXTI */
	EXTI_Init(&EXTI_InitStruct);

	/* Add IRQ vector to NVIC */
	/* PB4is connected to EXTI_Line4, which has EXTI4_IRQn vector */
	NVIC_InitStruct.NVIC_IRQChannel = EXTI4_IRQn;
	/* Set priority */
	NVIC_InitStruct.NVIC_IRQChannelPreemptionPriority = 0x00;
	/* Set sub priority */
	NVIC_InitStruct.NVIC_IRQChannelSubPriority = 0x00;
	/* Enable interrupt */
	NVIC_InitStruct.NVIC_IRQChannelCmd = ENABLE;
	/* Add to NVIC */
	NVIC_Init(&NVIC_InitStruct);
}

void Configure_PB5(void) {
	/* Set variables used */
	GPIO_InitTypeDef GPIO_InitStruct;
	EXTI_InitTypeDef EXTI_InitStruct;
	NVIC_InitTypeDef NVIC_InitStruct;
	
	/* Enable clock for GPIOB */
	RCC_AHB1PeriphClockCmd(RCC_AHB1Periph_GPIOB, ENABLE);
	/* Enable clock for SYSCFG */
	RCC_APB2PeriphClockCmd(RCC_APB2Periph_SYSCFG, ENABLE);
	
	/* Set pin as input */
	GPIO_InitStruct.GPIO_Mode = GPIO_Mode_IN;
	GPIO_InitStruct.GPIO_OType = GPIO_OType_PP;
	GPIO_InitStruct.GPIO_Pin = GPIO_Pin_5;
	//GPIO_InitStruct.GPIO_PuPd = GPIO_PuPd_UP;
	GPIO_InitStruct.GPIO_PuPd = GPIO_PuPd_DOWN;
	GPIO_InitStruct.GPIO_Speed = GPIO_Speed_100MHz;
	GPIO_Init(GPIOB, &GPIO_InitStruct);
	
	/* Tell system that you will use PB5 for EXTI_Line5 */
	SYSCFG_EXTILineConfig(EXTI_PortSourceGPIOB, EXTI_PinSource5);
	
	/* PB5 is connected to EXTI_Line5 */
	EXTI_InitStruct.EXTI_Line = EXTI_Line5;
	/* Enable interrupt */
	EXTI_InitStruct.EXTI_LineCmd = ENABLE;
	/* Interrupt mode */
	EXTI_InitStruct.EXTI_Mode = EXTI_Mode_Interrupt;
	/* Triggers on rising and falling edge */
	EXTI_InitStruct.EXTI_Trigger = EXTI_Trigger_Rising;
	//EXTI_InitStruct.EXTI_Trigger = EXTI_Trigger_Falling;
	//EXTI_InitStruct.EXTI_Trigger = EXTI_Trigger_Rising_Falling;
	/* Add to EXTI */
	EXTI_Init(&EXTI_InitStruct);

	/* Add IRQ vector to NVIC */
	/* PB5 is connected to EXTI_Line5, which has EXTI9_5_IRQn vector */
	NVIC_InitStruct.NVIC_IRQChannel = EXTI9_5_IRQn;
	//NVIC_InitStruct.NVIC_IRQChannel = EXTI15_10_IRQn;
	/* Set priority */
	NVIC_InitStruct.NVIC_IRQChannelPreemptionPriority = 0x00;
	/* Set sub priority */
	NVIC_InitStruct.NVIC_IRQChannelSubPriority = 0x01;
	/* Enable interrupt */
	NVIC_InitStruct.NVIC_IRQChannelCmd = ENABLE;
	/* Add to NVIC */
	NVIC_Init(&NVIC_InitStruct);
}

void intD4()
{
    us4 = SYSTEM_TICK_COUNTER;
    d4++;
    digitalWrite(D7, !digitalRead(D7));
}

int triggerInterrupt(String dmy)
{
    us2=us3=us4=0;
    us=SYSTEM_TICK_COUNTER;
    pinSetFast(D0);
    delayMicroseconds(10);
    pinResetFast(D0);
    
    return d4;
}

void dmy() { }

void setup() 
{
    /* System init */
	//SystemInit(); // BREAKS CLOUD
	/* Configure D3 as interrupt */
	Configure_PB4();
	/* Configure D2 as interrupt */
	Configure_PB5();
	
    Particle.function("trig", triggerInterrupt);
    
    pinMode(D0, OUTPUT);
    pinMode(D7, OUTPUT);

    us=SYSTEM_TICK_COUNTER;
    pinResetFast(D0);
    offset = SYSTEM_TICK_COUNTER - us;
    
    pinMode(D4, INPUT_PULLDOWN);
    attachInterrupt(D4, intD4, RISING);
}

void loop()
{
    if(us4)
    {
        char txt[256];
        snprintf(txt, sizeof(txt), "%12d ns (%5d): %12d ns (%5d): %12d ns (%5d)"
                                 , (us2-us-offset)*1000/SYSTEM_US_TICKS, d2
                                 , (us3-us-offset)*1000/SYSTEM_US_TICKS, d3
                                 , (us4-us-offset)*1000/SYSTEM_US_TICKS, d4
                );
        Serial.println(txt);
        Particle.publish("intTimes", txt, PRIVATE);
        us4 = 0;
    }
}
```
_(tested on Photon 0.6.0-rc.2)_

Currently the NVIC table seems to reside in flash, preventing any updates. 
How can we relocate it back to RAM without breaking HAL and why does it have to be in flash to start with?

---

Completeness:
- [X] Minimum test case added
- [X] Device, system and user firmware versions stated

### LINKED ISSUE #1333: How to Attach usr function to PVD IRQ handle for photon?
I want to save data to EEPROM when main power lose.
I find out Photon API does not support attach user functions to PVD IRQ Handdle 
I have try to modify the hal/src/photon/core_hal.c

When I am try to CC my APP:
```
/firmware-0.6.1/user/applications/air/main.cpp:66: undefined reference to `Attach_LMP_Irq'
```
Did I make any mistakes?

```
//hal/src/photon/core_hal.c
void (*Lose_Main_Power)(void) = NULL;

void Attach_LMP_Irq(void (*LMP)(void))
{
        Lose_Main_Power = LMP;
}

static void PVD_irq(void)
{
        EXTI_ClearITPendingBit(EXTI_Line16);
        if (PWR_GetFlagStatus(PWR_FLAG_PVDO)) {
                if (NULL != Lose_Main_Power) {
                        Lose_Main_Power();
                }
        }
}

void HAL_Core_Setup_override_interrupts(void) {

    memcpy(&link_ram_interrupt_vectors_location, &link_interrupt_vectors_location, &link_ram_interrupt_vectors_location_end-&link_ram_interrupt_vectors_location);
    uint32_t* isrs = (uint32_t*)&link_ram_interrupt_vectors_location;
    isrs[HardFaultIndex] = (uint32_t)HardFault_Handler;
    isrs[MemManageIndex] = (uint32_t)MemManage_Handler;
    isrs[BusFaultIndex] = (uint32_t)BusFault_Handler;
    isrs[UsageFaultIndex] = (uint32_t)UsageFault_Handler;
    isrs[SysTickIndex] = (uint32_t)SysTickOverride;
    isrs[USART1Index] = (uint32_t)HAL_USART1_Handler;
    isrs[USART2Index] = (uint32_t)HAL_USART2_Handler;
    isrs[ButtonExtiIndex] = (uint32_t)Mode_Button_EXTI_irq;
    isrs[TIM7Index] = (uint32_t)TIM7_override;  // WICED uses this for a JTAG watchdog handler
    isrs[DMA2Stream2Index] = (uint32_t)DMA2_Stream2_irq_override;
    isrs[CAN2_TX_IRQHandler_Idx]            = (uint32_t)CAN2_TX_irq;
    isrs[CAN2_RX0_IRQHandler_Idx]           = (uint32_t)CAN2_RX0_irq;
    isrs[CAN2_RX1_IRQHandler_Idx]           = (uint32_t)CAN2_RX1_irq;
    isrs[CAN2_SCE_IRQHandler_Idx]           = (uint32_t)CAN2_SCE_irq;
 //--------------------PVD--------------------------------
    isrs[PVD_Index] = (uint32_t)PVD_irq;

    SCB->VTOR = (unsigned long)isrs;
}

/hal/inc/core_hal.h
extern void Attach_LMP_Irq(void (*LMP)(void));
```

### PR DESCRIPTION
**Pull request by avtolstoy**
<details>
  <summary><i>submission notes</i></summary>

```
**Important:** Please sanitize/remove any confidential info like usernames, passwords, org names, product names/ids, access tokens, client ids/secrets, or anything else you don't wish to share.

Please Read and Sign the Contributor License Agreement ([Info here](https://github.com/spark/firmware/blob/develop/CONTRIBUTING.md)).

You may also delete this submission notes header if you'd like. Thank you for contributing!
```
</details>

### Problem

See #1168 #1333

### Solution

This PR adds two wiring functions `attachInterruptDirect()` and `detachInterruptDirect()` that allow the user code to directly insert interrupt handlers into the interrupt vector table.

### Steps to Test

- `wiring/no_fixture`: `INTERRUPTS_04_attachInterruptDirect`

### Example App

```c++
void pvd_irqn_handler() {
    // Do something
}

void setup() {
    attachInterruptDirect(PVD_IRQn, pvd_irqn_handler);
}

void loop() {

}
```

### References

- Closes #1168 
- Closes #1333
- [CH7827]

---

### Completeness

- [x] User is totes amazing for contributing!
- [x] Contributor has signed CLA ([Info here](https://github.com/spark/firmware/blob/develop/CONTRIBUTING.md))
- [x] Problem and Solution clearly stated
- [ ] Run unit/integration/application tests on device
- [ ] **TODO:** Add documentation
- [ ] Added to CHANGELOG.md after merging (add links to docs and issues)

### CODE REVIEW

**Comment by pkourany** [comment]
Reminder to review!

**Comment by m-mcgowan** [comment]
Are you psychic...I was literally reviewing this when you commented!

**Comment by pkourany** [comment]
I'll try and test with SparkIntervalTimer and a scope.  This is an important one to release as soon as its ready IMO.

**Comment by pkourany** [comment]
I tried this feature branch with my SparkIntervalTimer library coupled with my RGBPongClock and I get a hard fault.  I will test with a more basic app (blink LED) along with the SparkIntervalTimer library next.

**Comment by pkourany** [comment]
I tried a simple app with SparkIntervalTimer (using attachInterruptDirect()) and I get hard fault immediately after flashing over the code.  If I compile with regular `attachInterrupt()` the code works fine.

To test, I simply change the original code using `attachInterrupt()` such as this line:
`attachSystemInterrupt(SysInterrupt_TIM3_Update, Wiring_TIM3_Interrupt_Handler_override)`
to:
`attachInterruptDirect(TIM3_IRQn, Wiring_TIM3_Interrupt_Handler_override)`

**Comment by avtolstoy** [comment]
@pkourany I've just built SparkIntervalTimer with minimal changes:
```c++
        if (!attachInterruptDirect(TIM3_IRQn, Wiring_TIM3_Interrupt_Handler_override)) ; //error
        if (!attachInterruptDirect(TIM4_IRQn, Wiring_TIM4_Interrupt_Handler_override)) ; //error
        if (!attachInterruptDirect(TIM5_IRQn, Wiring_TIM5_Interrupt_Handler_override)) ; //error
        if (!attachInterruptDirect(TIM6_DAC_IRQn, Wiring_TIM6_Interrupt_Handler_override));  //error
        if (!attachInterruptDirect(TIM7_IRQn, Wiring_TIM7_Interrupt_Handler_override));  //error
```

and used the example provided with it, and it does not crash. Don't have a scope at hand, but at the very least D7 is flashing as intended.

**Comment by pkourany** [comment]
@avtolstoy, as I read your post I realized that with all my testing, I failed to update the system firmware parts!  I'll test again just to confirm.  Thanks!

**Comment by pkourany** [comment]
@avtolstoy, I must be missing something.  I checked out the branch, go to the firmware/modules directory and build/flash the system firmware and app using:

make clean all PLATFORM=photon APP=rgbpcFastInt program-dfu

Everything compiles and flashes but same hard fault.  What am I missing?

**Comment by pkourany** [comment]
Tested with SparkIntervalTimer (with some overdue mods) and it works.  Good to go!

**Comment by m-mcgowan** [comment]
Paul, what was the cause of the hard fault? Anything we need to look into?

**Comment by m-mcgowan** [comment]
Who's going to write up the docs for this?

**Comment by ScruffR** [comment]
Will there be a version of `attachInterruptDirect()` that also allows to provide a priority parameter as `attachInterrupt()` already does?

**Pull request merged**
