### PR TITLE
encapsulates cloud connect flag 

### PR DESCRIPTION
**Pull request by m-mcgowan**
renames the `SPARK_CONNECT` internal flag to `SPARK_AUTO_CONNECT` and encapsulates access behind some functions. This will help ensure that the auto connect state isn't cleared unintentionally.

### CODE REVIEW

**Comment by m-mcgowan** [comment]
Please review, @monkbroc

**Comment by monkbroc** [comment]
@m-mcgowan There are now 2 identically named functions [spark_disconnect](https://github.com/spark/firmware/blob/ebd3bf0e2c179ec701316074c6cd6696cf5c67b8/system/src/system_mode.cpp#L33) and [Spark_Disconnect](https://github.com/spark/firmware/blob/ebd3bf0e2c179ec701316074c6cd6696cf5c67b8/system/src/system_cloud_internal.cpp#L900). Same for spark_connect.

I suggest renaming
`spark_connect` :arrow_right: `spark_cloud_connect`
`spark_disconnect` :arrow_right: `spark_cloud_disconnect`
`spark_auto_connect` :arrow_right: `spark_cloud_auto_connect`

**Comment by m-mcgowan** [comment]
Yes, it's pretty horrid the current naming and use of uppercase. I'd like to rename all the functions to be more distinctive - the two families of functions operate on the "intent to connect" flag and on the actual socket connection.

```
spark_connect() -> spark_cloud_flag_connect()
Spark_Connect() -> spark_cloud_socket_connect();
```

I'm using Eclipse - I'd love to know why it makes such a mess of formatting. (Although not staying with Eclipse for long, I have my eyes on CLion....)

**Comment by monkbroc** [comment]
I updated the names with your suggestion. If the Travis builds work I'd say this is ready.

**Pull request merged**
