### PR TITLE
A test for SPI DMA issue #791 fixed in PR #801

### PR DESCRIPTION
**Pull request by avtolstoy**
This test checks the issue #791 of SPI User callback firing before the actual SPI transfer has finished.

### CODE REVIEW

**Comment by m-mcgowan** [comment]
@technobly  would you mind testing this - I don't have the required hardware.

**Comment by technobly** [comment]
@avtolstoy I've tested this on a Photon and Electron with the FRAM Shield and all 4 tests pass
```
make clean all PLATFORM_ID=6 TEST=wiring/spi_shield COMPILE_LTO=n -s program-dfu
```
However, I don't see the SPI user callback worked into test 4.  Was this meant to be included or is the fix from #791 tested by some other method?

**Comment by avtolstoy** [comment]
@technobly It should pass with develop branch, however it should fail on test 4 with v0.4.8 for example. Basically the test disables SPI right after the user callback is called and forcefully pulls MISO line low. The result is that if the callback is called before the transfer is completed, the last bytes will not be received at all or received with errors (since we pull MISO low). I've confirmed that this works in loopback mode and in theory should work with actual hardware as well.

**Comment by technobly** [comment]
Tested with v0.4.7 on Photon, this test fails #4 with FRAM shield.  Also this PR with Photon and Electron both pass all tests in FRAM shield.

**Pull request merged**
