### PR TITLE
Suggested sudo for Linux users and fix "makes silences" to just "silences".

### PR DESCRIPTION
**Pull request by gl2748**
Suggested sudo for Linux users and fix "makes silences" to just "silences".

---

Doneness:
- [x] Contributor has signed CLA (N/A docs only change)
- [x] Problem and Solution clearly stated
- [x] Code peer reviewed
- [x] API tests compiled
- [x] Run unit/integration/application tests on device
- [x] Add documentation
- [x] Add to CHANGELOG.md after merging (add links to docs and issues)

### CODE REVIEW

**Comment by nrobinson2000** [comment]
Hi gl

**Comment by nrobinson2000** [comment]
@monkbroc has created a udev rules file for using dfu without sudo. [here it is](https://gist.github.com/monkbroc/b283bb4da8c10228a61e)

**Comment by nrobinson2000** [comment]
It would be good to reference it here.

Or we should mention the utility I created to assist in installing dependencies, using the toolchain and dfu-util. [po-util: the Particle Offline Utility](https://github.com/nrobinson2000/po-util)

**Comment by monkbroc** [comment]
Hi, I work for Particle now so I'll see about including the udev rules in the firmware repository and including instructions to install those: ` sudo cp 50-particle.rules /etc/udev/rules.d/50-particle.rules`

**Comment by gl2748** [comment]
Hi nrob and monk, wherever is easiest, following the instructions without mentioning the need to be root, does not work.

**Pull request merged**
