### PR TITLE
Break listening loop before disabling listening mode in multithreaded setup

### LINKED ISSUE #743: Photon remains in listening mode after WiFi.listen(false)
My code (which I haven't tried boiling down to a minimal example yet) is running on a Photon with SYSTEM_THREAD(ENABLED); and firmware version 0.4.7 installed.

I call WiFi.listen(true) to put the Photon into listening mode, and it does so correctly (on-board LED switches to blue flash, and Photon WiFi AP shows up on my nearby iPhone). 

I later call WiFi.listen(false) to take the Photon out of listening mode, but nothing changes.

Is there a known problem with WiFi.listen(false) not working?

### PR DESCRIPTION
**Pull request by sergeuz**
Fixes #743

### CODE REVIEW

**Comment by sergeuz** [comment]
@m-mcgowan I'm not sure that reusing WLAN_SMART_CONFIG_START as a loop flag is a good idea here, so any thoughts are welcomed

**Comment by m-mcgowan** [comment]
Those changes look good. In the long run, I'd to break out the listening loop so that it doesn't lock up the system thread, but for now this is a good approach. 

You're right to raise which flag to use. I think here `WLAN_SERIAL_CONFIG_DONE` would be a better fit here since that flag exists to terminate the listen loop.  It's not a strong preference, but seems to better reflect the semantics of what we are doing here. 

An aside - the flag could be renamed to something more generic like, NETWORK_LISTEN_COMPLETE to make the intent clear, although feel free to leave that to a later revisiting of the code where we fix all the flags.

**Comment by sergeuz** [comment]
I've updated PR accordingly. Thanks)

**Comment by m-mcgowan** [comment]
I cherry picked the key change from your PR #793, which does the same job as this PR, so closing out.

**Pull request closed without merging**
