### PR TITLE
First attempt to implement user-configurable USART settings

### PR DESCRIPTION
**Pull request by joaodafonseca**
working fine, would be really handy

### CODE REVIEW

**Comment by m-mcgowan** [comment]
Thanks for this @joaodafonseca!  Please rebase on the develop branch so we can include it in the next release. Many thanks!

**Comment by joaodafonseca** [comment]
@m-mcgowan, @jmekler was the one who implement the user-configurable USART settings.

**Comment by tomtruitt** [comment]
Is it possible to enable 9 bit communication? I was told by someone at particle that it is "partially supported" but firmware needs to updated to allow...

**Comment by technobly** [comment]
Superseded by #757 and #930

**Pull request closed without merging**
