### PR TITLE
[0.5.x] Libraries V2 support

### PR DESCRIPTION
**Pull request by technobly**
Originally from PR #1009 and #1053 

Required infrastructure for Libraries V2 support.

---

Doneness:

- [x] Contributor has signed CLA
- [x] Problem and Solution clearly stated
- [x] Code peer reviewed
- [x] API tests compiled
- [x] Run unit/integration/application tests on device
- [ ] Add documentation
- [x] Add to CHANGELOG.md after merging (add links to docs and issues)

### ENHANCEMENTS

- Automatically adds vendored libraries from the `lib` directory for extended application projects [#1053](https://github.com/spark/firmware/pull/1053)

### INTERNAL

- Feature/vendorlibraries [#1009](https://github.com/spark/firmware/pull/1009)

### CODE REVIEW

**Comment by monkbroc** [comment]
Thanks for this Brett!

**Comment by Bacichetti** [comment]
@technobly, can I use a pre-compile library (mylib.a and mylib.h) with this new feature?

**Comment by Bacichetti** [comment]
I believe I found the answer. If I'm right I don't really need to compile the system firmware, I only need to make changes to the make file including my custom library before locally compiling my application, like it's explained on this part of the documentation, right?

[https://github.com/spark/firmware/blob/develop/docs/build.md#custom-makefile](url)

**Comment by technobly** [comment]
That sounds right @Bacichetti if you want your custom library in user firmware space, you can compile from the `firmware/main` directory and it will build just the user module.

**Pull request merged**
